import pandas as pd

da = pd.read_csv("data.csv")
print(da)
print("---==========================================")
print(da.shape)
print("---==========================================")
print(da.head(2))
print("---==========================================")
print(da.tail(3))
print("---==========================================")
print(da[2:5])
print("=============================================")
print(da.columns)
print("=============================================")
print(da[['Date','Event']])
print("=============================================")
print(da.Tempreture.max())
print(da.Tempreture.min())
print(da.Tempreture.mean())
print(da.Tempreture.std())
print("=============================================")
print(da.describe())
print("=============================================")
print(da[["Date","Tempreture"]][da.Tempreture==da.Tempreture.max()])